builds:
  - id: gitfive
    main: ./cmd/gitfive
    binary: gitfive
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/zackey-heuristics/gitfive-go/internal/version.Version={{.Version}} -X github.com/zackey-heuristics/gitfive-go/internal/version.Commit={{.ShortCommit}}

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
